name: Build & Publish Docker Image

inputs:
  app-name:
    type: string
    description: 'App name'
    required: true
  version:
    type: string
    description: 'Version string'
    required: true
  token:
    type: string
    description: Docker Hub Token
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    name: Checkout
  - name: Build and Publish Docker Image
    shell: bash
    run: |
      docker build --tag bossanova456/${{inputs.app-name}} --tag bossanova456/${{inputs.app-name}}:${{inputs.version}} .
      docker login -u bossanova456 -p ${{inputs.token}}
      docker push bossanova456/${{inputs.app-name}}