name: Build & Publish Docker Image

inputs:
  app-name:
    type: string
    description: 'App name'
    required: true
  version:
    type: string
    description: 'Version string'
    required: true
  token:
    type: string
    description: Docker Hub Token
    required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      name: Build and Publish Docker Image
      run: |
        docker build --tag bossanova456/${{inputs.app-name}} bossanova456/${{inputs.app-name}}:${{inputs.version}} .
        docker login -u bossanova456 -p ${{inputs.token}}
        docker push bossanova456/${{inputs.app-name}}